// frontend-salud/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { NavbarComponent } from './components/navbar/navbar';
import { FooterComponent } from './components/footer/footer';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterModule, NavbarComponent, FooterComponent],
  template: `
    <app-navbar></app-navbar>
    <main>
      <router-outlet></router-outlet>
    </main>
    <app-footer></app-footer>
  `,
  styles: []
})
export class AppComponent {}

<div class="app">
  <header class="app-header">
    <h1>🏥 Aplicación de Salud</h1>
    <p>Frontend desplegado en Railway</p>
  </header>

  <main class="app-main">
    <div class="health-check">
      <h2>Estado del Backend</h2>
      <button (click)="checkHealth()" [disabled]="loading">
        {{ loading ? 'Verificando...' : 'Verificar Conexión' }}
      </button>

      <div *ngIf="healthStatus" class="status success">
        <p><strong>Estado:</strong> {{ healthStatus.status }}</p>
        <p><strong>Mensaje:</strong> {{ healthStatus.message }}</p>
      </div>

      <div *ngIf="error" class="status error">
        <p><strong>Error:</strong> {{ error }}</p>
        <p>Verifica que el backend esté corriendo en: {{ apiUrl }}</p>
      </div>
    </div>

    <div class="info">
      <h3>Información del Deployment</h3>
      <ul>
        <li><strong>Frontend:</strong> Railway</li>
        <li><strong>Backend:</strong> Railway</li>
        <li><strong>API URL:</strong> {{ apiUrl }}</li>
      </ul>
    </div>

    <div class="contenidos-medicos">
      <h2>📚 Contenidos Médicos</h2>
      <button (click)="cargarContenidos()" [disabled]="loadingContenidos">
        {{ loadingContenidos ? 'Cargando...' : 'Recargar Contenidos' }}
      </button>

      <div *ngIf="loadingContenidos" class="status info">
        <p>Cargando contenidos médicos...</p>
      </div>

      <div *ngIf="errorContenidos" class="status error">
        <p><strong>Error:</strong> {{ errorContenidos }}</p>
      </div>

      <div *ngIf="!loadingContenidos && contenidos.length > 0" class="contenidos-grid">
        <div *ngFor="let contenido of contenidos" class="contenido-card">
          <h3>{{ contenido.titulo || 'Sin título' }}</h3>
          <span *ngIf="contenido.categoria" class="badge">{{ contenido.categoria }}</span>
          <p *ngIf="contenido.descripcion" class="descripcion">{{ contenido.descripcion }}</p>
          <p *ngIf="contenido.contenido" class="contenido">{{ getContenidoPreview(contenido.contenido) }}</p>
          <p *ngIf="contenido.tipo" class="tipo"><small>Tipo: {{ contenido.tipo }}</small></p>
        </div>
      </div>

      <div *ngIf="!loadingContenidos && !errorContenidos && contenidos.length === 0" class="status info">
        <p>No hay contenidos disponibles</p>
      </div>
    </div>
  </main>
</div>

// frontend-salud/src/App.jsx
import { useState, useEffect } from 'react'
import axios from 'axios'
import './App.css'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080'

function App() {
  const [healthStatus, setHealthStatus] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  const checkHealth = async () => {
    setLoading(true)
    setError(null)
    try {
      const response = await axios.get(`${API_URL}/api/health`)
      setHealthStatus(response.data)
    } catch (err) {
      setError(err.message)
      setHealthStatus(null)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    checkHealth()
  }, [])

  return (
    <div className="app">
      <header className="app-header">
        <h1>🏥 Aplicación de Salud</h1>
        <p>Frontend desplegado en Vercel</p>
      </header>

      <main className="app-main">
        <div className="health-check">
          <h2>Estado del Backend</h2>
          <button onClick={checkHealth} disabled={loading}>
            {loading ? 'Verificando...' : 'Verificar Conexión'}
          </button>

          {healthStatus && (
            <div className="status success">
              <p><strong>Estado:</strong> {healthStatus.status}</p>
              <p><strong>Mensaje:</strong> {healthStatus.message}</p>
            </div>
          )}

          {error && (
            <div className="status error">
              <p><strong>Error:</strong> {error}</p>
              <p>Verifica que el backend esté corriendo en: {API_URL}</p>
            </div>
          )}
        </div>

        <div className="info">
          <h3>Información del Deployment</h3>
          <ul>
            <li><strong>Frontend:</strong> Vercel</li>
            <li><strong>Backend:</strong> Railway</li>
            <li><strong>API URL:</strong> {API_URL}</li>
          </ul>
        </div>
      </main>
    </div>
  )
}

export default App
